import type WeightGroup from './WeightGroup'

export type Scene = {
  id: number
  name: string
  sources: number[] // Array of ContentSource IDs
  useWeights: boolean

  timingFunction: string
  timingConstant: number
  timingMin: number
  timingMax: number
  timingSinRate: number
  timingBPMMulti: number
  backForth: boolean
  backForthTF: string
  backForthConstant: number
  backForthMin: number
  backForthMax: number
  backForthSinRate: number
  backForthBPMMulti: number
  imageType: string
  backgroundType: string
  backgroundColor: string
  backgroundColorSet: string[]
  backgroundBlur: number

  imageTypeFilter: string
  fullSource: boolean
  imageOrientation: string
  gifOption: string
  gifTimingConstant: number
  gifTimingMin: number
  gifTimingMax: number
  videoOrientation: string
  videoOption: string
  videoTimingConstant: number
  videoTimingMin: number
  videoTimingMax: number
  videoSpeed: number
  videoRandomSpeed: boolean
  videoSpeedMin: number
  videoSpeedMax: number
  videoSkip: number
  randomVideoStart: boolean
  continueVideo: boolean
  playVideoClips: boolean
  skipVideoStart: number
  skipVideoEnd: number
  videoVolume: number
  weightFunction: string
  sourceOrderFunction: string
  forceAllSource: boolean
  orderFunction: string
  forceAll: boolean

  zoom: boolean
  zoomRandom: boolean
  zoomStart: number
  zoomStartMin: number
  zoomStartMax: number
  zoomEnd: number
  zoomEndMin: number
  zoomEndMax: number
  horizTransType: string
  horizTransLevel: number
  horizTransLevelMin: number
  horizTransLevelMax: number
  horizTransRandom: boolean
  vertTransType: string
  vertTransLevel: number
  vertTransLevelMin: number
  vertTransLevelMax: number
  vertTransRandom: boolean
  transTF: string
  transDuration: number
  transDurationMin: number
  transDurationMax: number
  transSinRate: number
  transBPMMulti: number
  transEase: string
  transExp: number
  transAmp: number
  transPer: number
  transOv: number

  crossFade: boolean
  crossFadeAudio: boolean
  fadeTF: string
  fadeDuration: number
  fadeDurationMin: number
  fadeDurationMax: number
  fadeSinRate: number
  fadeBPMMulti: number
  fadeEase: string
  fadeExp: number
  fadeAmp: number
  fadePer: number
  fadeOv: number

  slide: boolean
  slideTF: string
  slideType: string
  slideDistance: number
  slideDuration: number
  slideDurationMin: number
  slideDurationMax: number
  slideSinRate: number
  slideBPMMulti: number
  slideEase: string
  slideExp: number
  slideAmp: number
  slidePer: number
  slideOv: number

  strobe: boolean
  strobePulse: boolean
  strobeLayer: string
  strobeOpacity: number
  strobeTF: string
  strobeTime: number
  strobeTimeMin: number
  strobeTimeMax: number
  strobeSinRate: number
  strobeBPMMulti: number
  strobeDelayTF: string
  strobeDelay: number
  strobeDelayMin: number
  strobeDelayMax: number
  strobeDelaySinRate: number
  strobeDelayBPMMulti: number
  strobeColorType: string
  strobeColor: string
  strobeColorSet: string[]
  strobeEase: string
  strobeExp: number
  strobeAmp: number
  strobePer: number
  strobeOv: number

  fadeInOut: boolean
  fadeIOPulse: boolean
  fadeIOTF: string
  fadeIODuration: number
  fadeIODurationMin: number
  fadeIODurationMax: number
  fadeIOSinRate: number
  fadeIOBPMMulti: number
  fadeIODelayTF: string
  fadeIODelay: number
  fadeIODelayMin: number
  fadeIODelayMax: number
  fadeIODelaySinRate: number
  fadeIODelayBPMMulti: number
  fadeIOStartEase: string
  fadeIOStartExp: number
  fadeIOStartAmp: number
  fadeIOStartPer: number
  fadeIOStartOv: number
  fadeIOEndEase: string
  fadeIOEndExp: number
  fadeIOEndAmp: number
  fadeIOEndPer: number
  fadeIOEndOv: number

  panning: boolean
  panTF: string
  panDuration: number
  panDurationMin: number
  panDurationMax: number
  panSinRate: number
  panBPMMulti: number
  panHorizTransType: string
  panHorizTransImg: boolean
  panHorizTransLevel: number
  panHorizTransLevelMax: number
  panHorizTransLevelMin: number
  panHorizTransRandom: boolean
  panVertTransType: string
  panVertTransImg: boolean
  panVertTransLevel: number
  panVertTransLevelMax: number
  panVertTransLevelMin: number
  panVertTransRandom: boolean
  panStartEase: string
  panStartExp: number
  panStartAmp: number
  panStartPer: number
  panStartOv: number
  panEndEase: string
  panEndExp: number
  panEndAmp: number
  panEndPer: number
  panEndOv: number

  overrideIgnore: boolean
  scriptScene: boolean
  downloadScene: boolean
  generatorMax: number
  persistAudio: boolean
  persistText: boolean
  libraryID: number
  audioScene: boolean
  audioEnabled: boolean
  audioPlaylists: number[] // Array of audio playlist IDs
  audioStartIndex: number
  textEnabled: boolean
  scriptPlaylists: number[] // Array of script playlist IDs
  scriptStartIndex: number
  regenerate: boolean
  generatorWeights?: WeightGroup[]
}
