/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Audio {
  album: string | null
  artist: string | null
  bpm: number | null
  comment: string | null
  duration: number | null
  id: number | null
  marked: number
  name: string | null
  nextSceneAtEnd: number
  playedCount: number | null
  speed: number | null
  stopAtEnd: number
  thumb: string | null
  tick: number
  tickBpmMulti: number | null
  tickDelay: number | null
  tickMaxDelay: number | null
  tickMinDelay: number | null
  tickMode: string | null
  tickSinRate: number | null
  trackNum: number | null
  url: string
  userId: number
  volume: number | null
}

export interface AudioPlaylistItem {
  audioId: number
  id: number | null
  index: number
  playlistId: number
}

export interface AudioTag {
  audioId: number
  id: number | null
  tagId: number
}

export interface CacheSettings {
  directory: string | null
  enabled: number
  id: number | null
  maxSize: number
  userId: number
}

export interface CaptionScript {
  blinkFontId: number | null
  captionBigFontId: number | null
  captionFontId: number | null
  countFontId: number | null
  id: number | null
  marked: number
  nextSceneAtEnd: number
  opacity: number | null
  script: string | null
  stopAtEnd: number
  syncWithAudio: number
  url: string | null
  userId: number
}

export interface CaptionScriptPlaylistItem {
  captionScriptId: number
  id: number | null
  index: number
  playlistId: number
}

export interface CaptionScriptTag {
  captionScriptId: number
  id: number | null
  tagId: number
}

export interface Clip {
  contentSourceId: number
  disabled: number
  end: number | null
  id: number | null
  start: number | null
  userId: number
  volume: number | null
}

export interface ClipTag {
  clipId: number
  id: number | null
  tagId: number
}

export interface ContentSource {
  count: number
  countComplete: number
  id: number | null
  lastCheck: number | null
  localDirOfSources: number
  marked: number
  offline: number
  redditFunc: string | null
  redditTime: string | null
  twitterIncludeReplies: number
  twitterIncludeRetweets: number
  url: string
  userId: number
  videoDuration: number | null
  videoResolution: number | null
  videoSubtitleFile: string | null
  weight: number
}

export interface ContentSourceBlacklistItem {
  contentSourceId: number
  id: number | null
  url: string
}

export interface ContentSourceTag {
  contentSourceId: number
  id: number | null
  tagId: number
}

export interface Display {
  id: number | null
  name: string
  sceneGroupId: number | null
  userId: number
}

export interface DisplayPlaylistItem {
  duration: number | null
  id: number | null
  index: number
  playlistId: number
}

export interface DisplayPlaylistItemDisplay {
  displayId: number
  displayPlaylistItemId: number
  id: number | null
}

export interface DisplaySettings {
  audioAlert: number
  clickToProgress: number
  clickToProgressWhilePlaying: number
  easingControls: number
  fullScreen: number
  id: number | null
  maxInHistory: number
  maxInMemory: number
  maxLoadingAtOnce: number
  minImageSize: number
  minVideoSize: number
  startImmediately: number
  userId: number
}

export interface DisplayView {
  color: string
  displayId: number
  height: number
  id: number | null
  mirrorSyncedView: string
  name: string
  opacity: number
  playlistId: number | null
  sync: number
  syncWithView: number | null
  visible: number
  width: number
  x: number
  y: number
  z: number
}

export interface FontSettings {
  border: number
  borderColor: string | null
  borderpx: number | null
  color: string | null
  fontFamily: string | null
  fontSize: number | null
  id: number | null
  userId: number
}

export interface GeneralSettings {
  autoBackup: number
  autoBackupDays: number
  autoCleanBackup: number
  autoCleanBackupDays: number
  autoCleanBackupMonths: number
  autoCleanBackupWeeks: number
  cleanRetain: number
  confirmBlacklist: number
  confirmFileDeletion: number
  confirmSceneDeletion: number
  disableLocalSave: number
  id: number | null
  portableMode: number
  prioritizePerformance: number
  userId: number
  watermark: number
  watermarkColor: string
  watermarkCorner: string
  watermarkDisplay: number
  watermarkFontFamily: string
  watermarkFontSize: number
  watermarkText: string | null
}

export interface IgnoredTag {
  displaySettingsId: number
  id: number | null
  tagId: number
}

export interface LibraryContentSource {
  contentSourceId: number
  id: number | null
  userId: number
}

export interface Playlist {
  id: number | null
  name: string
  repeat: string
  sceneGroupId: number | null
  shuffle: number
  type: string
  userId: number
}

export interface RemoteSettings {
  hydrusApiKey: string | null
  hydrusDomain: string | null
  hydrusPort: number | null
  hydrusProtocol: string | null
  id: number | null
  instagramPassword: string | null
  instagramUsername: string | null
  piwigoHost: string | null
  piwigoPassword: string | null
  piwigoProtocol: string | null
  piwigoUsername: string | null
  redditClientId: string | null
  redditDeviceId: string | null
  redditRefreshToken: string | null
  redditUserAgent: string | null
  silenceTumblrAlert: number
  tumblrKey: string | null
  tumblrOauthToken: string | null
  tumblrOauthTokenSecret: string | null
  tumblrSecret: string | null
  twitterAccessTokenKey: string | null
  twitterAccessTokenSecret: string | null
  twitterConsumerKey: string | null
  twitterConsumerSecret: string | null
  userId: number
}

export interface Scene {
  audioEnabled: number
  audioScene: number
  audioStartIndex: number | null
  backForth: number
  backForthBpmMulti: number | null
  backForthConstant: number | null
  backForthMax: number | null
  backForthMin: number | null
  backForthSinRate: number | null
  backForthTf: string | null
  backgroundBlur: number | null
  backgroundType: string | null
  continueVideo: number
  crossFade: number
  crossFadeAudio: number
  defaultScene: number
  downloadScene: number
  fadeAmp: number | null
  fadeBpmMulti: number | null
  fadeDuration: number | null
  fadeDurationMax: number | null
  fadeDurationMin: number | null
  fadeEase: string | null
  fadeExp: number | null
  fadeInOut: number
  fadeIoBpmMulti: number | null
  fadeIoDelay: number | null
  fadeIoDelayBpmMulti: number | null
  fadeIoDelayMax: number | null
  fadeIoDelayMin: number | null
  fadeIoDelaySinRate: number | null
  fadeIoDelayTf: string | null
  fadeIoDuration: number | null
  fadeIoDurationMax: number | null
  fadeIoDurationMin: number | null
  fadeIoEndAmp: number | null
  fadeIoEndEase: string | null
  fadeIoEndExp: number | null
  fadeIoEndOv: number | null
  fadeIoEndPer: number | null
  fadeIoPulse: number
  fadeIoSinRate: number | null
  fadeIoStartAmp: number | null
  fadeIoStartEase: string | null
  fadeIoStartExp: number | null
  fadeIoStartOv: number | null
  fadeIoStartPer: number | null
  fadeIoTf: string | null
  fadeOv: number | null
  fadePer: number | null
  fadeSinRate: number | null
  fadeTf: string | null
  forceAll: number
  forceAllSource: number
  fullSource: number
  generatorMax: number | null
  gifOption: string | null
  gifTimingConstant: number | null
  gifTimingMax: number | null
  gifTimingMin: number | null
  horizTransLevel: number | null
  horizTransLevelMax: number | null
  horizTransLevelMin: number | null
  horizTransRandom: number
  horizTransType: string | null
  id: number | null
  imageOrientation: string | null
  imageType: string | null
  imageTypeFilter: string | null
  libraryId: number | null
  name: string
  orderFunction: string | null
  overrideIgnore: number
  panBpmMulti: number | null
  panDuration: number | null
  panDurationMax: number | null
  panDurationMin: number | null
  panEndAmp: number | null
  panEndEase: string | null
  panEndExp: number | null
  panEndOv: number | null
  panEndPer: number | null
  panHorizTransImg: number
  panHorizTransLevel: number | null
  panHorizTransLevelMax: number | null
  panHorizTransLevelMin: number | null
  panHorizTransRandom: number
  panHorizTransType: string | null
  panning: number
  panSinRate: number | null
  panStartAmp: number | null
  panStartEase: string | null
  panStartExp: number | null
  panStartOv: number | null
  panStartPer: number | null
  panTf: string | null
  panVertTransImg: number
  panVertTransLevel: number | null
  panVertTransLevelMax: number | null
  panVertTransLevelMin: number | null
  panVertTransRandom: number
  panVertTransType: string | null
  persistAudio: number
  persistText: number
  playVideoClips: number
  randomVideoStart: number
  regenerate: number
  sceneGroupId: number | null
  scriptScene: number
  scriptStartIndex: number | null
  skipVideoEnd: number | null
  skipVideoStart: number | null
  slide: number
  slideAmp: number | null
  slideBpmMulti: number | null
  slideDistance: number | null
  slideDuration: number | null
  slideDurationMax: number | null
  slideDurationMin: number | null
  slideEase: string | null
  slideExp: number | null
  slideOv: number | null
  slidePer: number | null
  slideSinRate: number | null
  slideTf: string | null
  slideType: string | null
  sourceOrderFunction: string | null
  strobe: number
  strobeAmp: number | null
  strobeBpmMulti: number | null
  strobeColorType: string | null
  strobeDelay: number | null
  strobeDelayBpmMulti: number | null
  strobeDelayMax: number | null
  strobeDelayMin: number | null
  strobeDelaySinRate: number | null
  strobeDelayTf: string | null
  strobeEase: string | null
  strobeExp: number | null
  strobeLayer: string | null
  strobeOpacity: number | null
  strobeOv: number | null
  strobePer: number | null
  strobePulse: number
  strobeSinRate: number | null
  strobeTf: string | null
  strobeTime: number | null
  strobeTimeMax: number | null
  strobeTimeMin: number | null
  textEnabled: number
  timingBpmMulti: number | null
  timingConstant: number | null
  timingFunction: string | null
  timingMax: number | null
  timingMin: number | null
  timingSinRate: number | null
  transAmp: number | null
  transBpmMulti: number | null
  transDuration: number | null
  transDurationMax: number | null
  transDurationMin: number | null
  transEase: string | null
  transExp: number | null
  transOv: number | null
  transPer: number | null
  transSinRate: number | null
  transTf: string | null
  userId: number
  useWeights: number
  vertTransLevel: number | null
  vertTransLevelMax: number | null
  vertTransLevelMin: number | null
  vertTransRandom: number
  vertTransType: string | null
  videoOption: string | null
  videoOrientation: string | null
  videoRandomSpeed: number
  videoSkip: number | null
  videoSpeed: number | null
  videoSpeedMax: number | null
  videoSpeedMin: number | null
  videoTimingConstant: number | null
  videoTimingMax: number | null
  videoTimingMin: number | null
  videoVolume: number | null
  weightFunction: string | null
  zoom: number
  zoomEnd: number | null
  zoomEndMax: number | null
  zoomEndMin: number | null
  zoomRandom: number
  zoomStart: number | null
  zoomStartMax: number | null
  zoomStartMin: number | null
}

export interface SceneColor {
  color: string
  id: number | null
  sceneId: number
  type: string
}

export interface SceneContentSource {
  contentSourceId: number
  id: number | null
  sceneId: number
}

export interface SceneGroup {
  id: number | null
  name: string
  type: string
  userId: number
}

export interface ScenePlaylist {
  id: number | null
  playlistId: number
  sceneId: number
}

export interface ScenePlaylistItem {
  duration: number | null
  id: number | null
  index: number
  playAfterAllImages: number
  playlistId: number
}

export interface ScenePlaylistItemScene {
  id: number | null
  sceneId: number
  scenePlaylistItemId: number
}

export interface Sessions {
  expired: string | null
  sess: string | null
  sid: string | null
}

export interface Tag {
  id: number | null
  name: string
  phraseString: string | null
  userId: number
}

export interface Theme {
  id: number | null
  mode: string | null
  primaryColor: string | null
  secondaryColor: string | null
  userId: number
}

export interface Tutorials {
  audios: string | null
  current: string | null
  id: number | null
  library: string | null
  player: string | null
  sceneDetail: string | null
  sceneGenerator: string | null
  scenePicker: string | null
  scriptor: string | null
  scripts: string | null
  userId: number
  videoClipper: string | null
}

export interface User {
  hashedPassword: Buffer
  id: number | null
  salt: Buffer
  tokenExpiry: number | null
  tokenValue: string | null
  username: string
}

export interface WeightGroup {
  chosen: number | null
  id: number | null
  max: number | null
  percent: number | null
  ruleId: number | null
  sceneId: number
  search: string | null
  type: string | null
}

export interface DB {
  audio: Audio
  audioPlaylistItem: AudioPlaylistItem
  audioTag: AudioTag
  cacheSettings: CacheSettings
  captionScript: CaptionScript
  captionScriptPlaylistItem: CaptionScriptPlaylistItem
  captionScriptTag: CaptionScriptTag
  clip: Clip
  clipTag: ClipTag
  contentSource: ContentSource
  contentSourceBlacklistItem: ContentSourceBlacklistItem
  contentSourceTag: ContentSourceTag
  display: Display
  displayPlaylistItem: DisplayPlaylistItem
  displayPlaylistItemDisplay: DisplayPlaylistItemDisplay
  displaySettings: DisplaySettings
  displayView: DisplayView
  fontSettings: FontSettings
  generalSettings: GeneralSettings
  ignoredTag: IgnoredTag
  libraryContentSource: LibraryContentSource
  playlist: Playlist
  remoteSettings: RemoteSettings
  scene: Scene
  sceneColor: SceneColor
  sceneContentSource: SceneContentSource
  sceneGroup: SceneGroup
  scenePlaylist: ScenePlaylist
  scenePlaylistItem: ScenePlaylistItem
  scenePlaylistItemScene: ScenePlaylistItemScene
  sessions: Sessions
  tag: Tag
  theme: Theme
  tutorials: Tutorials
  user: User
  weightGroup: WeightGroup
}
