name: Manual Test Release

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      arch:
        description: 'True to print to STDOUT'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - x64
          - arm64

jobs:
  build:
    if: ${{ inputs.os != 'windows.latest' || inputs.arch != 'arm64'}}
    runs-on: ${{ inputs.os }}
    env:
      PLATFORM: ${{ inputs.os == 'ubuntu-latest' && 'linux' || (inputs.os == 'windows-latest' && 'win' || 'macos') }}
      PLATFORM_NAME: ${{ inputs.os == 'ubuntu-latest' && 'linux' || (inputs.os == 'windows-latest' && 'windows' || 'macos') }}
      EXTENSION: ${{ inputs.os == 'windows-latest' && '.exe' || '' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Enable Yarn
      run: |
        corepack enable
        corepack prepare yarn@stable --activate
    - name: Install Common
      working-directory: ./common
      run: yarn install --immutable
    - name: Build Common Main
      working-directory: ./common
      run: yarn build:main
    - name: Build Common Module
      working-directory: ./common
      run: yarn build:module      
    - name: Install Client
      working-directory: ./client
      run: yarn install --immutable
    - name: Build Client
      working-directory: ./client
      run: yarn build
    - name: Get Package Version
      id: get-package-version
      uses: stevenbenitez/get-package-version-action@v1
      with:
        path: ./server
    - name: Install Server
      working-directory: ./server
      run: yarn install --immutable
    - name: Install FFProbe
      uses: actions/github-script@v7
      env:
        OS: ${{ inputs.os }}
        ARCH: ${{ inputs.arch }}
      with:
        script: |
          const fs = require('fs')
          const path = require('path')
          const { Readable } = require('stream');
          const { finished } = require('stream/promises');

          const downloadFile = async (url, destination) => {
            const res = await fetch(url);
            const fileStream = fs.createWriteStream(destination, { flags: 'wx' });
            await finished(Readable.fromWeb(res.body).pipe(fileStream));
          };

          const targets = {}
          targets['ubuntu-latest'] = 'linux'
          targets['windows-latest'] = 'win32'
          targets['macos-latest'] = 'darwin'
          const target = `${targets[process.env.OS]}-${process.env.ARCH}`

          const ffprobePath = path.resolve('./server', 'node_modules', '@ffprobe-installer', target)
          if(!fs.existsSync(ffprobePath)) {
            await fs.promises.mkdir(ffprobePath)
            const executable = process.env.OS == 'windows-latest' ? 'ffprobe.exe' : 'ffprobe'
            const files = ['package.json', executable]
            for (const file of files) {
              const url = `https://github.com/SavageCore/node-ffprobe-installer/raw/refs/tags/v2.1.2/platforms/${target}/${file}`
              await downloadFile(url, path.join(ffprobePath, file))
            }
          }

    - name: Build server
      working-directory: ./server
      run: yarn prod
    - name: Move client output to server
      run: mv ./client/dist ./server/bin/public/
    - name: Create package
      working-directory: ./server
      run: yarn pkg -t node22-${{ env.PLATFORM }}-${{ inputs.arch }} .
    - name: Show ffprobe output
      working-directory: ./server
      run: ls -al ./node_modules/@ffprobe-installer
    - name: Show build output
      working-directory: ./server
      run: ls -al ./dist