name: Pull Request

on:
  pull_request:
    branches: [v4.0.0]

jobs:
  common:
    uses: ./.github/workflows/module-check.yml
    with:
      display-name: Common
      working-directory: ./common
      format-task: test:prettier
      build-task: build:main
      build-task-extra: build:module
  client:
    uses: ./.github/workflows/module-check.yml
    with:
      display-name: Client
      working-directory: ./client
      depends-on-common: true
      do-lint-task: false
  server:
    uses: ./.github/workflows/module-check.yml
    with:
      display-name: Server
      working-directory: ./server
      build-task: tsc
      depends-on-common: true
  test:
    needs: [common, client, server]
    timeout-minutes: 60
    if: ${{ needs.client.outputs.run_tests == 'true' || needs.server.outputs.run_tests == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: ["ubuntu-22.04","macos-13","windows-2022"]
    steps:
    - name: macos-13 dependencies fix
      if: ${{ matrix.os == 'macos-13' }}
      run: sudo -H pip install setuptools
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Enable Yarn
      run: |
        corepack enable
        corepack prepare yarn@stable --activate
    - name: Install Common
      working-directory: ./common
      run: yarn install --immutable
    - name: Build Common Main
      working-directory: ./common
      run: yarn build:main
    - name: Build Common Module
      working-directory: ./common
      run: yarn build:module      
    - name: Install Client
      working-directory: ./client
      run: yarn install --immutable
    - name: Install Server
      working-directory: ./server
      run: yarn install --immutable
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps --only-shell
      working-directory: ./server
    - name: Run Playwright tests
      run: bash ./playwright.sh
      working-directory: ./server
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.os }}
        path: ./server/playwright-report/
        retention-days: 30
