name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            arch: [x64, arm64]
    env:
      PLATFORM: ${{ matrix.os == 'ubuntu-latest' && 'linux' || (matrix.os == 'windows-latest' && 'win32' || 'darwin') }}
      PLATFORM_NAME: ${{ matrix.os == 'ubuntu-latest' && 'Linux' || (matrix.os == 'windows-latest' && 'Windows' || 'Mac') }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 26
    - name: Enable corepack
      run: corepack enable
    - name: Enable Yarn
      run: corepack prepare yarn@stable --activate
    - name: Install packages
      run: corepack yarn install
    - name: Make Release
      run: corepack yarn make --platform ${{ env.PLATFORM }} --arch ${{ matrix.arch }}
    - name: Rename Release Asset
      run: |
        node -e "
        const fs = require('fs');
        const path = require('path');
        const dir = path.resolve('./out/make/zip/${{ env.PLATFORM }}/${{ matrix.arch }}');
        const file = fs.readdirSync(dir).find(fn => fn.startsWith('FlipFlip-${{ env.PLATFORM }}-${{ matrix.arch }}-') && fn.endsWith('.zip'));
        fs.renameSync(path.join(dir, file), path.join(dir, file.replace('${{ env.PLATFORM }}', '${{ env.PLATFORM_NAME }}')));
        "
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: softprops/action-gh-release@v3
      with:
        working_directory: out/make/zip/${{ env.PLATFORM }}/${{ matrix.arch }}
        files: |
          FlipFlip-${{ env.PLATFORM_NAME }}-${{ matrix.arch }}-*.zip