name: Release

on:
  release:
    types: [published, edited]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
  build:
    runs-on: ${{ matrix.target.os }}
    strategy:
        matrix:
          target: [
            { os: "ubuntu-22.04", platform: "linux", arch: "x64" }, 
            { os: "ubuntu-22.04-arm", platform: "linux", arch: "arm64" }, 
            { os: "macos-13", platform: "macos", arch: "x64" }, 
            { os: "macos-14", platform: "macos", arch: "arm64" }, 
            { os: "windows-2022", platform: "win", arch: "x64" }
          ]
    env:
      EXTENSION: ${{ matrix.target.os == 'windows-2022' && '.exe' || '' }}
    steps:
    - name: Install setuptools
      if: ${{matrix.target.platform == 'macos'}}
      run: brew install python-setuptools
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Enable Yarn
      run: |
        corepack enable
        corepack prepare yarn@stable --activate
    - name: Install Common
      working-directory: ./common
      run: yarn install --immutable
    - name: Build Common Main
      working-directory: ./common
      run: yarn build:main
    - name: Build Common Module
      working-directory: ./common
      run: yarn build:module      
    - name: Install Client
      working-directory: ./client
      run: yarn install --immutable
    - name: Build Client
      working-directory: ./client
      run: yarn build
    - name: Get Package Version
      id: get-package-version
      uses: stevenbenitez/get-package-version-action@v1
      with:
        path: ./server
    - name: Install Server
      working-directory: ./server
      run: yarn install --immutable
    - name: Build server
      working-directory: ./server
      run: yarn prod
    - name: Move client output to server
      run: mv ./client/dist ./server/bin/public/
    - name: Create package
      working-directory: ./server
      run: yarn pkg -t node22-${{ matrix.target.platform }}-${{ matrix.target.arch }} --compress Brotli .
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./server/dist/server${{ env.EXTENSION }}
        asset_name: FlipFlip-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ steps.get-package-version.outputs.version }}${{ env.EXTENSION }}
        asset_content_type: application/octet-stream